### ISSUE TITLE
If tdi2 is set to True, then the code fails due to a typo 

### ISSUE THREAD

**Issue by karnesis** [mikekatz04/GBGPU#3]
As the title says. The proposed fix would be to replace lines 328-333 in the gbgpu.py file with

`        if tdi2:`
`            omegaL = 2 * np.pi * f0 * (Larm / Clight)`
`            tdi2_factor = 2.0j * self.xp.sin(2 * omegaL) * self.xp.exp(-2j * omegaL)`
`            fctr *= tdi2_factor`
`        XYZf *= fctr[:, None, None]`

**Comment by mikekatz04** [comment]
fixed thanks!
