### ISSUE TITLE
ModuleNotFoundError: Sensitivity curve information through LISA Analysis Tools is not available. Stock option for Information matrix will not work. Please install LISA Analysis Tools (lisatools)

### ISSUE THREAD

**Issue by mx-Liu123** [mikekatz04/GBGPU#4]
Hi!

After installation, I run "python -m unittest discover" and get following error:

/home/svu/e1101894/.local/lib/python3.8/site-packages/gbgpu-0.1-py3.8-linux-x86_64.egg/gbgpu/gbgpu.py:24: UserWarning: tdi module not found. No sensitivity information will be included.
  warnings.warn("tdi module not found. No sensitivity information will be included.")
/home/svu/e1101894/.local/lib/python3.8/site-packages/gbgpu-0.1-py3.8-linux-x86_64.egg/gbgpu/utils/utility.py:15: UserWarning: tdi module not found. No sensitivity information will be included.
  warnings.warn("tdi module not found. No sensitivity information will be included.")
/home/svu/e1101894/.local/lib/python3.8/site-packages/gbgpu-0.1-py3.8-linux-x86_64.egg/gbgpu/utils/utility.py:264: UserWarning: Sensitivity information not available. The number of points in the waveform will not be determined byt the signal strength without the availability of the Sensitivity.
  warnings.warn(
.E..
======================================================================
ERROR: test_information_matrix (test_gbgpu.WaveformTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/svu/e1101894/pureLHS/GBGPU/gbgpu/tests/test_gbgpu.py", line 196, in test_information_matrix
    info_matrix = gb.information_matrix(
  File "/home/svu/e1101894/.local/lib/python3.8/site-packages/gbgpu-0.1-py3.8-linux-x86_64.egg/gbgpu/gbgpu.py", line 1015, in information_matrix
    raise ModuleNotFoundError(
ModuleNotFoundError: Sensitivity curve information through LISA Analysis Tools is not available. Stock option for Information matrix will not work. Please install LISA Analysis Tools (lisatools).

----------------------------------------------------------------------
Ran 4 tests in 0.966s

FAILED (errors=1)

It seems that I need to install lisatools but the only code I found online is many years ago and based on python2. Is this one the lisatools I am supposed to install?

https://github.com/vallis/lisatools/tree/master

Thanks!

**Comment by mikekatz04** [comment]
Yes this is correct. Thanks you. Keep in mind LISA Analysis tools is in beta version. The initial full release is coming soon.

**Comment by mx-Liu123** [comment]
Sounds good! I previously don't have access to the LISA Analysis tools, now it is available to me. Thanks a lot.

**Comment by GeorgySk** [comment]
I've just noticed that this error can also appear when lisatools is installed but the lisatools itself is missing some of its dependencies. For example, I didn't have SciPy installed which resulted in `ModuleNotFoundError` being thrown in _lisatools/sensitivity.py_. That error, in turn, got propagated to GBGPU and, finally, resulted in the error in the title. This is confusing and should be addressed, IMHO.
