### ISSUE TITLE
Error during installation with CUDA: "nvcc fatal   : Unsupported gpu architecture 'compute_35'"

### ISSUE THREAD

**Issue by GeorgySk** [mikekatz04/GBGPU#7]
When trying to install GBPU with CUDA 12.2, I'm getting the following error:
```
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.9/site-packages/numpy/core/include -I/opt/local/include -I/usr/local/cuda/include -Iinclude -I/usr/local/include/python3.9 -c src/gbgpu_utils.cu -o build/temp.linux-x86_64-cpython-39/src/gbgpu_utils.o -arch=sm_70 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 --default-stream=per-thread --ptxas-options=-v -c --compiler-options '-fPIC' -lineinfo -Xcompiler -fopenmp
nvcc fatal   : Unsupported gpu architecture 'compute_35'
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
```
From what I understand CUDA 12.2 doesn't support the 'compute_35' architecture anymore. When commenting out the corresponding line here: https://github.com/mikekatz04/GBGPU/blob/540a002f99aa4dce0e7ba1be11e2419748cee150/setup.py#L140-L145 the error goes away. 

Ideally, I believe, this list of architectures should be generated automatically depending on the CUDA version. Or, maybe, there is a flag that would allow to include all supported architectures without specifying them explicitly?

**Comment by duboism** [comment]
Hello,

We had the same a few weeks ago. I unfortunately opened an issue (#8) without re-checking so I missed your. We came to the same conclusion.

**Comment by mikekatz04** [comment]
Thanks for this. I have removed 35 and will remove 50 soon probably. I am planning to migrate to setuptools-cuda within the next year.

**Comment by duboism** [comment]
Thank you for that. If we can help, just let us now.
